// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package donors

import (
	"database/sql"
)

type DonorAdjustment struct {
	PersonID    sql.NullString
	DisplayName sql.NullString
	Slug        sql.NullString
	Amount      sql.NullFloat64
}
